//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Putovanja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destinacija
    {
        public int idDestinacija { get; set; }
        public Nullable<int> idPutovanja { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public Nullable<System.DateTime> DatumPolaska { get; set; }
        public Nullable<System.DateTime> DatumPovratka { get; set; }
        public string VremeOd { get; set; }
        public string VremeDo { get; set; }
    
        public virtual Putovanje Putovanje { get; set; }
    }
}
