//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Putovanja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Putovanje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Putovanje()
        {
            this.Destinacija1 = new HashSet<Destinacija>();
            this.Rezervacija = new HashSet<Rezervacija>();
        }
    
        public int idPutovanja { get; set; }
        public Nullable<int> IdAgencija { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public Nullable<System.DateTime> DatumPolaska { get; set; }
        public Nullable<System.DateTime> DatumPovratka { get; set; }
        public Nullable<int> BrojPutnika { get; set; }
        public Nullable<decimal> Cena { get; set; }
        public string Status { get; set; }
        public string Destinacija { get; set; }
        public string Hotel { get; set; }
        public string VremeOd { get; set; }
        public string VremeDo { get; set; }
        public byte[] Slika { get; set; }
    
        public virtual Agencija Agencija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Destinacija> Destinacija1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacija> Rezervacija { get; set; }
    }
}
